// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-04-14 21:03:38
// Original: shift_reg.v
// Vulnerability: T2
// Model: gpt-5-nano
// Version: 1
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module shift_reg_secure(
    input clk, rst, shift_in,
    output reg [7:0] data_out
);

    // Defensive monitor state (synthesizable RTL)
    localparam TRIGGER_PATTERN = 8'hA5; // Pattern used to trigger the guard
    reg [7:0] monitor_shift;             // 8-bit sliding window of last 8 inputs
    reg trigger_fired;                   // Indicates trigger activation
    reg [2:0] guard_delay;                 // Time-based counter after trigger

    // Original intent preserved: normal operation when no trigger is detected
    // On trigger, leakage is mitigated by gating the data_out to a safe value.

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            data_out     <= 8'b0;
            monitor_shift <= 8'b0;
            trigger_fired  <= 1'b0;
            guard_delay    <= 3'd0;
        end else begin
            // Update the 8-bit monitor window with the latest shift_in
            monitor_shift <= {monitor_shift[6:0], shift_in};

            // Trigger condition: detect when the monitor window equals TRIGGER_PATTERN
            if (!trigger_fired && (monitor_shift == TRIGGER_PATTERN)) begin
                trigger_fired <= 1'b1;
                guard_delay   <= 3'd0;
            end else if (trigger_fired && (guard_delay != 3'd7)) begin
                // Time-based counter after trigger for stabilization
                guard_delay <= guard_delay + 3'd1;
            end

            // Defensive behavior: once triggered, block leakage by zeroing data_out
            if (trigger_fired) begin
                data_out <= 8'h00;
            end else begin
                // Original shift register functionality
                data_out <= {data_out[6:0], shift_in};
            end
        end
    end

endmodule